name: ci

on:
  push:
    branches:
      - develop
      - main
      - feature/build
  pull_request:
    branches:
      - develop
      - main

jobs:
  upload-data:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          path: resslab-hub-data
      - uses: actions/checkout@v3
        with:
          repository: RESSLab-Team/resslab-hub
          token: ${{ secrets.GH_PAT }}
          path: resslab-hub
          ref: develop
      - run: docker build -f Dockerfile-uploader -t resslab-hub-uploader .
        working-directory: "resslab-hub/backend"
      - run: docker run --rm -e ENV_FOR_DYNACONF=production -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -v $(pwd)/../../resslab-hub-data/:/opt/data resslab-hub-uploader all /opt/data
        working-directory: "resslab-hub/backend"
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
